UPDATE `AdminUser`
SET `role` = 'ADMIN_CAMPUS'
WHERE `role` IN ('SCOLARITE', 'RESPONSABLE_ACADEMIQUE', 'DECIDEUR');

ALTER TABLE `AdminUser`
MODIFY `role` ENUM('SUPER_ADMIN', 'ADMIN_CAMPUS') NOT NULL DEFAULT 'ADMIN_CAMPUS';